### ISSUE TITLE
Yeelight candela

### ISSUE THREAD

**Issue by otherguy** [hcoohb/hass-yeelightbt#5] opened 2020-09-20 16:24 UTC
Hi and thanks for your work on this component.

I was able to pair HA with my Yeelight Candela (`F8:24:41:C0:3B:7E yeelight_ms`). 

On / Off works perfectly, and brightness can be set, but the slider always reverts to a brightness of zero. I assume the code to read back the brightness does not work with these type of lamps.

If possible, you could also disable the color temperature and hue pickers, because they are not needed or used on such a lamp.

I'm happy to help with any information you might need!

**Comment by hcoohb** [comment] 2020-09-21 14:21
Hi,
Thanks for reporting the issue.
Yes I do not have a candela so could not try. They use a nearly identical bt protocol but it seems they expose the brightness differently. I have an idea on where the problem could be, but would you be able to [enable debug](https://github.com/hcoohb/hass-yeelightbt#debugging), restart HA, then:
- turn on, wait 5s
- change brightness to a low value, wait 5s
- change brightness to a high value, wait 5s
- turn off

And can you please post the log (only the lines relevant to the yeelight_bt component) ?
That way I can confirm, how the candela is reporting brightness.
Thanks

For removing temperature and hue pickers, totally doable but I need a way to identify the model. I will add more debug messaging in next release to try to identify the model, otherwise it could be a variable in the configuration

**Comment by ASNNetworks** [comment] 2020-09-22 20:54
I hope this is of any help!
```
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.yeelightbt] Writing  0x0100 on handle 35
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.yeelightbt] Writing  0x436702000000000000000000000000000000 on handle 31
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.yeelightbt] Received 0x436302000000000000000000000000000000 fron handle=34
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.yeelightbt] Yeelight pairing was successful!
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.yeelightbt] Writing  0x434225000000000000000000000000000000 on handle 31
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.yeelightbt] Received 0x434501250207080000000000000000000000 fron handle=34
2020-09-22 22:52:49 DEBUG (SyncWorker_47) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:52:49 DEBUG (SyncWorker_43) [custom_components.yeelight_bt.light] Requesting an update of the lamp status
2020-09-22 22:52:49 DEBUG (SyncWorker_43) [custom_components.yeelight_bt.yeelightbt] Get_state
2020-09-22 22:52:49 DEBUG (SyncWorker_43) [custom_components.yeelight_bt.yeelightbt] WAITING before next command
2020-09-22 22:52:50 DEBUG (SyncWorker_43) [custom_components.yeelight_bt.yeelightbt] Writing  0x434402000000000000000000000000000000 on handle 31
2020-09-22 22:52:50 DEBUG (SyncWorker_43) [custom_components.yeelight_bt.yeelightbt] Received 0x434501250207080000000000000000000000 fron handle=34
2020-09-22 22:52:50 DEBUG (SyncWorker_43) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:52:52 DEBUG (SyncWorker_27) [custom_components.yeelight_bt.light] Trying to turn on. with ATTR:{'color_temp': 200}
2020-09-22 22:52:52 DEBUG (SyncWorker_27) [custom_components.yeelight_bt.light] Trying to set temp: 5535
2020-09-22 22:52:52 DEBUG (SyncWorker_27) [custom_components.yeelight_bt.yeelightbt] Set_temperature 5535, 0
2020-09-22 22:52:52 DEBUG (SyncWorker_27) [custom_components.yeelight_bt.yeelightbt] Writing  0x4343159f0000000000000000000000000000 on handle 31
2020-09-22 22:52:52 DEBUG (SyncWorker_15) [custom_components.yeelight_bt.light] Requesting an update of the lamp status
2020-09-22 22:52:52 DEBUG (SyncWorker_15) [custom_components.yeelight_bt.yeelightbt] Get_state
2020-09-22 22:52:52 DEBUG (SyncWorker_15) [custom_components.yeelight_bt.yeelightbt] WAITING before next command
2020-09-22 22:52:53 DEBUG (SyncWorker_15) [custom_components.yeelight_bt.yeelightbt] Writing  0x434402000000000000000000000000000000 on handle 31
2020-09-22 22:52:53 DEBUG (SyncWorker_15) [custom_components.yeelight_bt.yeelightbt] Received 0x434501250207080000000000000000000000 fron handle=34
2020-09-22 22:52:53 DEBUG (SyncWorker_15) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:52:54 DEBUG (SyncWorker_57) [custom_components.yeelight_bt.light] Trying to turn on. with ATTR:{'brightness': 29}
2020-09-22 22:52:54 DEBUG (SyncWorker_57) [custom_components.yeelight_bt.light] Trying to set brightness: 11
2020-09-22 22:52:54 DEBUG (SyncWorker_57) [custom_components.yeelight_bt.yeelightbt] Set_brightness 11
2020-09-22 22:52:54 DEBUG (SyncWorker_57) [custom_components.yeelight_bt.yeelightbt] Writing  0x43420b000000000000000000000000000000 on handle 31
2020-09-22 22:52:54 DEBUG (SyncWorker_57) [custom_components.yeelight_bt.yeelightbt] Received 0x4345010b0207080000000000000000000000 fron handle=34
2020-09-22 22:52:54 DEBUG (SyncWorker_57) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:52:54 DEBUG (SyncWorker_14) [custom_components.yeelight_bt.light] Requesting an update of the lamp status
2020-09-22 22:52:54 DEBUG (SyncWorker_14) [custom_components.yeelight_bt.yeelightbt] Get_state
2020-09-22 22:52:54 DEBUG (SyncWorker_14) [custom_components.yeelight_bt.yeelightbt] WAITING before next command
2020-09-22 22:52:55 DEBUG (SyncWorker_14) [custom_components.yeelight_bt.yeelightbt] Writing  0x434402000000000000000000000000000000 on handle 31
2020-09-22 22:52:55 DEBUG (SyncWorker_14) [custom_components.yeelight_bt.yeelightbt] Received 0x4345010b0207080000000000000000000000 fron handle=34
2020-09-22 22:52:55 DEBUG (SyncWorker_14) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:53:01 DEBUG (SyncWorker_50) [custom_components.yeelight_bt.light] Requesting an update of the lamp status
2020-09-22 22:53:01 DEBUG (SyncWorker_50) [custom_components.yeelight_bt.yeelightbt] Get_state
2020-09-22 22:53:01 DEBUG (SyncWorker_50) [custom_components.yeelight_bt.yeelightbt] Writing  0x434402000000000000000000000000000000 on handle 31
2020-09-22 22:53:01 DEBUG (SyncWorker_30) [custom_components.yeelight_bt.light] Requesting an update of the lamp status
2020-09-22 22:53:01 DEBUG (SyncWorker_30) [custom_components.yeelight_bt.yeelightbt] Get_state
2020-09-22 22:53:01 DEBUG (SyncWorker_30) [custom_components.yeelight_bt.yeelightbt] Writing  0x434402000000000000000000000000000000 on handle 31
2020-09-22 22:53:01 DEBUG (SyncWorker_50) [custom_components.yeelight_bt.yeelightbt] Received 0x434501470207080000000000000000000000 fron handle=34
2020-09-22 22:53:01 DEBUG (SyncWorker_50) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:53:01 DEBUG (SyncWorker_30) [custom_components.yeelight_bt.yeelightbt] Received 0x4345010b0207080000000000000000000000 fron handle=34
2020-09-22 22:53:01 DEBUG (SyncWorker_30) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:53:11 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.light] Trying to turn on. with ATTR:{'brightness': 230}
2020-09-22 22:53:11 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.light] Trying to set brightness: 90
2020-09-22 22:53:11 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Set_brightness 90
2020-09-22 22:53:11 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Writing  0x43425a000000000000000000000000000000 on handle 31
2020-09-22 22:53:11 WARNING (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Device disconnected), Retrying now...
2020-09-22 22:53:11 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.light] Got state notification from the lamp
2020-09-22 22:53:12 WARNING (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Could not connect to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Failed to connect to peripheral F8:24:41:C2:1E:D1 yeelight_ms, addr type: public), Retrying in 0.1 seconds...
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Writing  0x0100 on handle 35
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Writing  0x436702000000000000000000000000000000 on handle 31
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Received 0x436302000000000000000000000000000000 fron handle=34
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Yeelight pairing was successful!
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Writing  0x43425a000000000000000000000000000000 on handle 31
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.yeelightbt] Received 0x4345015a0207080000000000000000000000 fron handle=34
2020-09-22 22:53:13 DEBUG (SyncWorker_1) [custom_components.yeelight_bt.light] Got state notification from the lamp

```

**Comment by hcoohb** [comment] 2020-09-23 13:45
Hi,

Thanks for that log!
It definitely shows that the candela is reporting the state differently, so I need to make the proper mapping for this, but we need to have a way to know what model it is. 

The state response from the lamp seems to report other values too. What is changeable on the candela? Is it just the brightness or can you change something else? And is there different modes?
I will push a new version soon that help reports versions which will help us confirm hopefully.

For the bt, connection, I have read that the candela shut the connections by itself in some cases to save battery. And the long part is establishing the connection (especially the bluepy library seems to take a long time to retry once there is an error). I am not sure as well if bluepy plays well with several devices to be controlled with this library.

**Comment by otherguy** [comment] 2020-09-23 14:34
Great and thanks @ASNNetworks because I didn’t get around to it yet ;)

On the candela, only the brightness is changeable. There is a “candle” mode in which it flickers like a candle. That’s all.

I can confirm that it shuts down the BT connections, even when it’s permanently connected to power.

**Comment by hcoohb** [comment] 2020-09-25 06:52
Hi guys,

I have released a version that **should** detect the candela by querying the device version (from what I could find online).
If a Candela is detected, it should then let HA know that only brightness is supported, as well as read the brightness correclty from the lamp.
Could one of you could use v0.10.5 and get similar log as above?
Also, if you can change the mode to candle with a physiscal button while the lamp is connected, I would be interested to know if that change the byte that I assume was the mode of the lamp in its status notification.

For the bt disconnection, if it is the lamp constantly disconnecting, I am afraid there is probably not that much that can be done. It will need to reconnect everytime a command is sent and everytime we are polling for status. We could lower the frequency of polling for the candela maybe...

**Comment by otherguy** [comment] 2020-09-25 09:12
Hey!

Thanks for the new version! I can confirm that the candela seems to be detected correctly. Only the brightness slider is shown and it does indeed reflect the brightness, at least if set from HA.

I noticed a few things. First of all, the (non-debug) log is flooded with messages like this:

```
2020-09-25 10:50:37 ERROR (SyncWorker_9) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int')
2020-09-25 10:51:06 WARNING (SyncWorker_52) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int'), Retrying now...
2020-09-25 10:51:07 WARNING (SyncWorker_52) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int'), Retrying now...
2020-09-25 10:51:07 ERROR (SyncWorker_52) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int')
2020-09-25 10:51:36 WARNING (SyncWorker_19) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int'), Retrying now...
2020-09-25 10:51:37 WARNING (SyncWorker_19) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int'), Retrying now...
2020-09-25 10:51:37 ERROR (SyncWorker_19) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'TypeError'>('<' not supported between instances of 'NoneType' and 'int')
```

The second thing I noticed is that the light state will switch to `Unavailable` for just a second, every time the brightness is adjusted, before then showing the correct value.

![2020-09-25 11-03-49 2020-09-25 11_06_00](https://user-images.githubusercontent.com/6072721/94249062-a4130380-ff1f-11ea-84a3-ffadcbff82cc.gif)


Manually adjusting the light (twisting the lamp to adjust brightness, not using HA) instantly causes it to go to `Unavailable` state which will then show this in the log:

```
2020-09-25 11:00:00 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.candela is taking over 10 seconds
2020-09-25 11:00:01 WARNING (SyncWorker_8) [custom_components.yeelight_bt.yeelightbt] Could not connect to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Failed to connect to peripheral F8:24:41:C0:3B:7E, addr type: public), Retrying in 0.1 seconds...
2020-09-25 11:07:20 WARNING (MainThread) [homeassistant.components.light] Updating yeelight_bt light took longer than the scheduled update interval 0:00:30
2020-09-25 11:07:50 WARNING (MainThread) [homeassistant.components.light] Updating yeelight_bt light took longer than the scheduled update interval 0:00:30
2020-09-25 11:08:20 WARNING (MainThread) [homeassistant.components.light] Updating yeelight_bt light took longer than the scheduled update interval 0:00:30
```

I can post full logs tomorrow.

**Comment by hcoohb** [comment] 2020-09-25 12:17
Oh, my bad, I have pushed 0.10.6 that hopefully fixes the TypeError for Candela.

For your second point:
For the bedside lamp, the component basically always maintain a connection to the lamp to be able to send command quickly and read new state quickly. So if there is a disconnection, I make the lamp unavailable since we cannot send cmd in that time. I believe that makes sense.
In case of the candela however it seems to always terminate the bt connection. So when the command for a different brightness is sent, the component realize then that it can't write and must reconnect. At that time, the status of the lamp is set to unavailable until we have made the new connection write value for brightness and get the status back from the lamp.
So it all comes from the fact the candela is stopping the bt connection.
We could try a different approach for the candela which is to only show the light as unavailable once we failed 3 attempted connections? Which I believe should remove this temporary unavailable when a command is sent (at least most of the time). I'll try to experiment with that on my bedside lamp over the weekend...

**Comment by hcoohb** [comment] 2020-09-28 13:17
Any luck with those new version?

I'd be keen if you could give me a log with all the info for the candela.
And maybe try a bluetooth scan from the integration menu?
And if you can change the mode manually on the lamp, cuz I assumed a few things on the values reported by the lamp, but not entirely certain as I can't test directly...

Thanks

**Comment by bluefoxlee** [comment] 2020-09-28 17:13
I have been trying to add Candela with HA for awhile. Appreciate for the hardworking. 
Add component 0.10.7, managed to get pair done for couple time. it Works great at first night and lost connection from second days.

Removed and use 0.11.1 with scan function. everything works great so far. (Pair, manual adjust lamp with status update - Slow but working). Will report back few days later.

Not sure if this log helps.

`2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.light] Requesting an update of the lamp status
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Get_state
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Trying to write  0x434402000000000000000000000000000000 on handle 31
2020-09-28 22:13:20 WARNING (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Device disconnected), Retrying now...
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Trying to write  0x0100 on handle 35
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Trying to write  0x436702000000000000000000000000000000 on handle 31
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Received 0x436302000000000000000000000000000000 fron handle=34
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Yeelight pairing was successful!
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Trying to write  0x434402000000000000000000000000000000 on handle 31
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] Received 0x434501640207080000000000000000000000 fron handle=34
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.yeelightbt] <Lamp f8:24:41:c0:0a:34 ON mode_White >
2020-09-28 22:13:20 DEBUG (SyncWorker_32) [custom_components.yeelight_bt.light] Got state notification from the lamp`

Again, Thanks.

**Comment by otherguy** [comment] 2020-10-04 12:55
On the latest version I get:

```
2020-10-04 14:44:02 WARNING (SyncWorker_9) [custom_components.yeelight_bt.yeelightbt] Could not connect to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Failed to connect to peripheral F8:24:41:C0:3B:7E, addr type: public), Retrying in 0.1 seconds...
2020-10-04 14:44:02 ERROR (SyncWorker_9) [custom_components.yeelight_bt.yeelightbt] Could not connect to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Failed to connect to peripheral F8:24:41:C0:3B:7E, addr type: public)
2020-10-04 14:44:32 WARNING (SyncWorker_4) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'bluepy.btle.BTLEInternalError'>(Helper not started (did you call connect()?)), Retrying now...
2020-10-04 14:44:37 WARNING (SyncWorker_4) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'bluepy.btle.BTLEException'>(Error from bluepy-helper (badparam)), Retrying now...
2020-10-04 14:44:37 ERROR (SyncWorker_4) [custom_components.yeelight_bt.yeelightbt] Could not write to lamp: error<class 'bluepy.btle.BTLEException'>(Error from bluepy-helper (badparam))
```

Or, if I reset hci0:

```
2020-10-04 14:48:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform yeelight_bt is taking over 10 seconds.
2020-10-04 14:49:30 ERROR (MainThread) [homeassistant.components.light] Setup of platform yeelight_bt is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2020-10-04 14:53:40 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward
```

Is this an issue with my bluetooth adapter?

**Comment by tcheronneau** [comment] 2020-10-23 13:33
I tried to add some of my new bulbs (not candela but still yeelight bt). 
And I've got the same issue as @otherguy.

**Comment by otherguy** [comment] 2020-11-05 22:35
Let us know how we can help you here!

**Comment by matteos1** [comment] 2021-09-15 21:09
Not work with candela.

**Comment by nightscout515** [comment] 2021-11-09 13:05
Thx candela works without any issues! One thing is so wanted : candle effect. If you can please add it. Thank you again.

**Comment by joshuavandermeulen** [comment] 2022-02-07 20:24
> Thx candela works without any issues! One thing is so wanted : candle effect. If you can please add it. Thank you again.

Hello @nightscout515, how did you manage to get the candela working? ha finds the candela but it is not possible to turn it on or off here...

**Comment by Koendejongh** [comment] 2022-04-05 18:14
Hi all,

same here. I can find the Candela, but it is unavailable. Anyone can help?

**Comment by nunokaneco** [comment] 2022-09-20 14:58
Hello To all 

I'm trying to adding the Yeelight candela to my home Assistant , i discover this but I not able to add the device with the scan or even if manual adding the mac address and the name 

![image](https://user-images.githubusercontent.com/33290686/191292307-8b36e786-927c-4456-abec-a208203f3d9e.png)

I Change the switch to the Bluetooth position when I try to add this devices and also after the adding manual I try to turn off tur on without sucess 

Can anyone please help me in order to solve this issue ? 

Thank you and best regards

**Comment by hcoohb** [comment] 2022-10-16 13:52
Duplicate of #29 

Let's keep only one active

**Closed by hcoohb** 2022-10-16 13:52 UTC
